### ISSUE TITLE
got a ValueError when running the script

### ISSUE THREAD

**Issue by eredi93** [awslabs/cost-optimization-ec2-right-sizing#3]
```
INFO:root:Finish to download EC2 pricelist file and upload it to S3 bucket: ec2pricelist.csv
INFO:root:Connected to the database
INFO:root:Importing the CloudWatch files to Redshift table
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:root:Finish to import the CloudWatch files to the Redshift table: cwdatapvbnrmgw
INFO:root:Importing the EC2 pricelist to Redshift
INFO:root:Generate Redshift table structure
INFO:root:Importing the pricelist files to Redshift table: pricelistcrxnwpqt
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:root:Finish to import the EC2 pricelist to Redshift table: pricelistcrxnwpqt
INFO:root:Analyzing the instances need to be resized
Complete percent: 1.0%Traceback (most recent call last):
  File "/tmp/run-rightsizing-redshift.py", line 434, in <module>
    ls_temp_table = right_sizing(conn, ls_pricelist_tabname, ls_cw_tabname)
  File "/tmp/run-rightsizing-redshift.py", line 376, in right_sizing
    determine_right_type(db_conn, ls_resizetype_sql, ls_temp_table, ls_instanceid, ln_iops_usage, ln_ssd_total_size, ln_cpu_nbr, ln_network_level_usage, ln_rate, ln_mem)
  File "/tmp/run-rightsizing-redshift.py", line 251, in determine_right_type
    ln_min_ssd_size = int(ls_min_storage1[ls_min_storage1.find('x')+1:])
ValueError: invalid literal for int() with base 10: '0.475 NVMe'
```

**Comment by milbrya** [comment]
Can you find the offending line in the file with the format YYYY-MM-DD-before336hour-with60min.csv.gz and post it here?

**Comment by eredi93** [comment]
how can i do that? in the file every line seems ok

**Comment by ryanaverill** [comment]
I'm getting the exact same error. I've searched through YYYY-MM-DD-before336hour-with60min.csv and I can't find it there either

Complete percent: 19.0%Traceback (most recent call last):
  File "/tmp/run-rightsizing-redshift.py", line 434, in <module>
    ls_temp_table = right_sizing(conn, ls_pricelist_tabname, ls_cw_tabname)
  File "/tmp/run-rightsizing-redshift.py", line 376, in right_sizing
    determine_right_type(db_conn, ls_resizetype_sql, ls_temp_table, ls_instanceid, ln_iops_usage, ln_ssd_total_size, ln_cpu_nbr, ln_network_level_usage, ln_rate, ln_mem)
  File "/tmp/run-rightsizing-redshift.py", line 251, in determine_right_type
    ln_min_ssd_size = int(ls_min_storage1[ls_min_storage1.find('x')+1:])
ValueError: invalid literal for int() with base 10: '0.475 NVMe'

**Comment by stevemorad** [comment]
Patches pushed that we believe fixes this issue -- checking SSD storage type is NVMe
